name: Netlify

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14.x

    steps:
      - name: Checkout source node
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run build
        env:
          REACT_APP_URI: ${{ secrets.REACT_APP_URI }}
          REACT_APP_MEN_NAME: ${{ secrets.REACT_APP_MEN_NAME }}
          REACT_APP_WOMEN_NAME: ${{ secrets.REACT_APP_WOMEN_NAME }}

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=./build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
